name: Gitleaks Check

on:
  push:
    branches:
      - master

jobs:
  gitleaks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Gitleaks
        run: |
          sudo apt-get update
          sudo apt-get install gitleaks -y

      - name: Run Gitleaks
        run: gitleaks detect
