#!/bin/bash

# Descarga e instala gitleaks si no está instalado
if ! command -v gitleaks &> /dev/null; then
  echo "Instalando gitleaks..."
  wget https://github.com/zricethezav/gitleaks/releases/download/v7.2.1/gitleaks-linux-amd64
  mv gitleaks-linux-amd64 gitleaks
  chmod +x gitleaks
  sudo mv gitleaks /usr/local/bin/
fi

# Ejecuta gitleaks
echo "Ejecutando gitleaks..."
gitleaks detect
