name: Gitleaks Check

on:
  push:
    branches:
      - master

jobs:
  gitleaks:
    name: Run Gitleaks
    runs-on: ubuntu-latest
    steps:
      - name: Set Node.js version to 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Gitleaks
        run: sudo apt-get update && sudo apt-get install gitleaks -y

      - name: Run Gitleaks
        run: gitleaks detect
